# Generated by Django 3.2.8 on 2022-06-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('idImpuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreImpuesto', models.CharField(max_length=30, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
    ]
