# Generated by Django 3.2.8 on 2022-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_alter_impuesto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
