# Generated by Django 3.2.8 on 2022-06-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0005_alter_impuesto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='estado',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='isestado',
            field=models.BooleanField(default=True),
        ),
    ]
