# Generated by Django 3.2.8 on 2022-06-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0008_remove_impuesto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCli', models.AutoField(primary_key=True, serialize=False)),
                ('CUIT', models.PositiveIntegerField(max_length=11)),
                ('claveFiscal', models.CharField(max_length=64, verbose_name='claveFiscal')),
                ('RazonSocial', models.CharField(max_length=50, verbose_name='RazonSocial')),
                ('isEstado', models.BooleanField(default=1)),
            ],
        ),
    ]
