# Generated by Django 4.0.5 on 2022-07-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0010_alter_cliente_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CUIT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='isEstado',
            field=models.BooleanField(),
        ),
    ]
