# Generated by Django 4.0.5 on 2022-07-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0011_alter_cliente_cuit_alter_cliente_isestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CUIT',
            field=models.CharField(max_length=11),
        ),
    ]
