# Generated by Django 4.0.5 on 2022-07-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0013_alter_cliente_isestado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impuesto',
        ),
    ]
