# Generated by Django 4.0.5 on 2022-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0014_delete_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='isEstado',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
