# Generated by Django 4.0.5 on 2022-07-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0015_alter_cliente_isestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='isEstado',
            field=models.BooleanField(default=1),
        ),
    ]
