# Generated by Django 4.0.5 on 2022-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0016_alter_cliente_isestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CUIT',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
